import "./globals.css";
import { DM_Sans, Barlow ,Dancing_Script } from "next/font/google";

const dmSans = DM_Sans({
  variable: "--font-dmSans",
  subsets: ["latin"],
  weight:["100","200","300","400","500","600","700","800","900"]
});

const barlow = Barlow({
  variable: "--font-barlow",
  subsets: ["latin"],
   weight:["100","200","300","400","500","600","700","800","900"]
});

const dancingScript = Dancing_Script({
  variable: "--font-dancing",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"]  // puedes ajustar según lo que necesites
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${dmSans.variable} ${barlow.variable} ${dancingScript.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
